CREATE TABLE VIN_APP.INSTITUTION (
    id VARCHAR(100) PRIMARY KEY NOT NULL,
    active TINYINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    startDate DATE NOT NULL,
    ableToAddEmployee TINYINT NOT NULL
);